from random import seed
from random import randint
# seed random number generator
seed(1)

import sys
original_stdout = sys.stdout # Save a reference to the original standard output

StringList = ["Hi, how are you?","It's me Prasoon","Man lets play chess!!!","Nvidia’s incoming R470 graphics driver will be the last to support some of the firm’s older graphics cards with performance optimizations, namely the GeForce GTX 600 and 700 range of GPUs, according to a new report. So, if you’re running one of those cards, you’ll need to bear that in mind (although note that the GTX 750 and its Ti variant are Maxwell, not Kepler). Of course at this point, even the newer GTX 700 series is eight years old now, so it’s going to be a shaky proposition in terms of contemporary gaming at this point anyway. AMD vs Nvidia: which should be your next graphics card? Where to buy Nvidia RTX 3080: find stock here Don’t forget that Amazon’s Prime Day 2021 sale is on the horizon As VideoCardz, which spotted Phoronix flagging this up courtesy of Nvidia’s data center documentation, points out, the R470 driver family will be the last to support graphics cards built with the Kepler architecture. We are currently on the R465 family of drivers, specifically version 466.47 which was released earlier this week, with R470 expected to debut in 2021, likely fairly soon.Once Nvidia moves to the next driver generation (presumably R475) – perhaps by the end of 2021, or early 2022 – the GTX 600 and 700 cards will no longer be supported in terms of optimization for games, meaning they’ll gradually deliver worse performance as time goes on. Security fixes Do note, though, that these GPUs will then be in LTS or long-term support with the R470 driver, so while the driver will no longer cater for optimization needs, it will still provide security fixes for any major vulnerabilities that could pop up in the future.Nvidia will deliver LTS support through until 2024, keeping Kepler users safe from security holes for another few years yet – meaning that GTX 600 graphics cards will actually be supported for a full 12 years from a security standpoint, a commendable length of time.Nvidia’s Maxwell GPUs, meaning the GTX 750 and GTX 900 series cards, will be next in line for the driver chopping block of course, but that shouldn’t be for a while yet (likely a couple of years down the line)."
,"Nvidia’s incoming R470 graphics driver will be the last to support some of the firm’s older graphics cards with performance optimizations, namely the GeForce GTX 600 and 700 range of GPUs, according to a new report. So, if you’re running one of those cards, you’ll need to bear that in mind (although note that the GTX 750 and its Ti variant are Maxwell, not Kepler). Of course at this point, even the newer GTX 700 series is eight years old now, so it’s going to be a shaky proposition in terms of contemporary gaming at this point anyway. AMD vs Nvidia: which should be your next graphics card? Where to buy Nvidia RTX 3080: find stock here Don’t forget that Amazon’s Prime Day 2021 sale is on the horizon As VideoCardz, which spotted Phoronix flagging this up courtesy of Nvidia’s data center documentation, points out, the R470 driver family will be the last to support graphics cards built with the Kepler architecture. We are currently on the R465 family of drivers, specifically version 466.47 which was released earlier this week, with R470 expected to debut in 2021, likely fairly soon.Once Nvidia moves to the next driver generation (presumably R475) – perhaps by the end of 2021, or early 2022 – the GTX 600 and 700 cards will no longer be supported in terms of optimization for games, meaning they’ll gradually deliver worse performance as time goes on. Security fixes Do note, though, that these GPUs will then be in LTS or long-term support with the R470 driver, so while the driver will no longer cater for optimization needs, it will still provide security fixes for any major vulnerabilities that could pop up in the future.Nvidia will deliver LTS support through until 2024, keeping Kepler users safe from security holes for another few years yet – meaning that GTX 600 graphics cards will actually be supported for a full 12 years from a security standpoint, a commendable length of time.Nvidia’s Maxwell GPUs, meaning the GTX 750 and GTX 900 series cards, will be next in line for the driver chopping block of course, but that shouldn’t be for a while yet (likely a couple of years down the line).", "Hi, how are you?","It's me Prasoon","Man lets play chess!!!"]

with open('dataset.txt', 'w') as f:
    sys.stdout = f # Change the standard output to the file we created.
    for i in range(0,50000): 
    	value = randint(0,7);
    	print(StringList[value])
sys.stdout = original_stdout